services:
  anpr-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nepal_anpr_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
